from loja import *
# Exemplo de uso:
produto1 = Produto(descricao = "Vestido", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/vestido1.png")
produto2 = Produto(descricao = "Blusa Regata Esportiva", situacao = "Tamanho: M, Usada", cor ="Branca", nome_imagem="imgs/blusa2.jpg")
produto3 = Produto(descricao = "Blusa Beagle", situacao = "Tamanho: P, Seminovo", cor ="Azul", nome_imagem="imgs/blusa3.jpg")
produto4 = Produto(descricao = "Blusa Pijama", situacao = "Tamanho: P, Usada", cor ="Cinza", nome_imagem="imgs/blusa4.jpg")
produto5 = Produto(descricao = "Blusa Queen", situacao = "Tamanho: P, Usada", cor ="Branca", nome_imagem="imgs/blusa5.jpg")
produto6 = Produto(descricao = "Blusa Girassol", situacao = "Tamanho: P, Usada", cor ="Cinza", nome_imagem="imgs/blusa6.jpg")
produto7 = Produto(descricao = "Blusa Harry Potter", situacao = "Tamanho: P, Usada", cor ="Cinza", nome_imagem="imgs/blusa7.jpg")
produto8 = Produto(descricao = "Blusa", situacao = "Tamanho: P, Usada", cor ="Preta", nome_imagem="imgs/blusa8.jpg")
produto9 = Produto(descricao = "Regata", situacao = "Tamanho: G, Usada", cor ="Preta", nome_imagem="imgs/blusa9.jpg")
produto10 = Produto(descricao = "Blusa Florida", situacao = "Tamanho: P, Usada", cor ="Branca", nome_imagem="imgs/blusa10.png")
produto11 = Produto(descricao = "Blusa Cropped Love", situacao = "Tamanho: P, Seminovo", cor ="Preta", nome_imagem="imgs/blusa11.png")
produto12 = Produto(descricao = "Blusa Cropped", situacao = "Tamanho: PP, Seminovo", cor ="Preto", nome_imagem="imgs/blusa12.png")
produto13 = Produto(descricao = "Blusa Cropped", situacao = "Tamanho: PP, Seminovo", cor ="Preto", nome_imagem="imgs/blusa13.png")
produto14 = Produto(descricao = "Blusa", situacao = "Tamanho: M, Usada", cor ="Branca", nome_imagem="imgs/blusa14.png")
produto15 = Produto(descricao = "Blusa Estampada", situacao = "Tamanho: M, Seminovo", cor ="Azul", nome_imagem="imgs/blusa15.png")
produto16 = Produto(descricao = "Blusa Cropped Nude", situacao = "Tamanho: P, Usado", cor ="Nude", nome_imagem="imgs/blusa16.png")
produto17 = Produto(descricao = "Blusa DC", situacao = "Tamanho: P, Usada", cor ="Cinza", nome_imagem="imgs/blusa17.png")
produto18 = Produto(descricao = "Blusa", situacao = "Tamanho: P, Usada", cor ="Preta", nome_imagem="imgs/blusa32.png")
produto19 = Produto(descricao = "Blusa", situacao = "Tamanho: P, Usada", cor ="Cinza", nome_imagem="imgs/blusa18.png")
produto20 = Produto(descricao = "Blusa", situacao = "Tamanho: P, Usada", cor ="Cinza", nome_imagem="imgs/blusa19.png")
produto21 = Produto(descricao = "Blusa Inverno", situacao = "Tamanho: G, Usada", cor ="Bege", nome_imagem="imgs/blusa20.png")
produto22 = Produto(descricao = "Blusa Esportivo", situacao = "Tamanho: P, Usada", cor ="Vermelho", nome_imagem="imgs/blusa21.png")
produto23 = Produto(descricao = "Blusa Florida", situacao = "Tamanho: M, Usada", cor ="Verde", nome_imagem="imgs/blusa22.png")
produto24 = Produto(descricao = "Blusa", situacao = "Tamanho: M, Seminovo", cor ="Cinza", nome_imagem="imgs/blusa23.png")
produto25 = Produto(descricao = "Blusa Rock", situacao = "Tamanho: P, Usada", cor ="Cinza", nome_imagem="imgs/blusa24.png")
produto26 = Produto(descricao = "Blusa de Renda", situacao = "Tamanho: P, Usada", cor ="Preta", nome_imagem="imgs/blusa25.png")
produto27 = Produto(descricao = "Blusa listrada", situacao = "Tamanho: M, Usada", cor ="Branca", nome_imagem="imgs/blusa26.png")
produto28 = Produto(descricao = "Blusa Love", situacao = "Tamanho: G, Usada", cor ="Cinza e rosa", nome_imagem="imgs/blusa27.png")
produto29 = Produto(descricao = "Blusa Estampada", situacao = "Tamanho: M, Usada", cor ="Bege", nome_imagem="imgs/blusa28.png")
produto30 = Produto(descricao = "Blusa Florida", situacao = "Tamanho: G, Usada", cor ="Rosa", nome_imagem="imgs/blusa29.png")
produto31 = Produto(descricao = "Blusa Basica", situacao = "Tamanho: M, Usada", cor ="Vermelho", nome_imagem="imgs/blusa30.png")
produto32 = Produto(descricao = "Blusa Cropped", situacao = "Tamanho: P, Usada", cor ="Branco", nome_imagem="imgs/blusa31.png")


produto33 = Produto(descricao = "Calça Moletom", situacao = "Situação: Seminovo", cor ="Preto", nome_imagem="imgs/calca1fem.jpg")
produto34 = Produto(descricao = "Calça Jeans Rasgada", situacao = "Situação: Seminovo", cor ="Jeans", nome_imagem="imgs/calca2fem.jpg")
produto35 = Produto(descricao = "Calça Jeans", situacao = "Situação: Seminovo", cor ="Jeans", nome_imagem="imgs/calca3fem.png")
produto36 = Produto(descricao = "Calça Jeans Escura", situacao = "Situação: Seminovo", cor ="Jeans", nome_imagem="imgs/calca4fem.png")
produto37 = Produto(descricao = "Calça Moletom", situacao = "Situação: Seminovo", cor ="Vermelha", nome_imagem="imgs/calca5fem.png")
produto38 = Produto(descricao = "Calça Jeans Escura", situacao = "Situação: Seminovo", cor ="Jeans", nome_imagem="imgs/calca6fem.png")
produto39 = Produto(descricao = "Calça Jeans Escura", situacao = "Situação: Seminovo", cor ="Jeans", nome_imagem="imgs/calca7fem.png")
produto40 = Produto(descricao = "Calça Jeans", situacao = "Situação: Seminovo", cor ="Branca", nome_imagem="imgs/calca8fem.png")
produto41 = Produto(descricao = "Calça Jeans Rasgada", situacao = "Situação: Seminovo", cor ="Jeans", nome_imagem="imgs/calca9fem.png")


produto42 = Produto(descricao = "Moletom", situacao = "Situação: Seminovo", cor ="Preto", nome_imagem="imgs/moletom1fem.jpg")
produto43 = Produto(descricao = "Moletom", situacao = "Situação: Seminovo", cor ="Vinho", nome_imagem="imgs/moletom2fem.jpg")

produto44 = Produto(descricao = "Shorts Jeans Claro", situacao = "Situação: Seminovo", cor ="Jeans", nome_imagem="imgs/short1fem.jpg")
produto45 = Produto(descricao = "Shorts Basico", situacao = "Situação: Seminovo", cor ="Cinza", nome_imagem="imgs/short2fem.jpg")
produto46 = Produto(descricao = "Shorts Esportivo", situacao = "Situação: Seminovo", cor ="Cinza", nome_imagem="imgs/short3fem.jpg")
produto47 = Produto(descricao = "Shorts Social", situacao = "Situação: Seminovo", cor ="Bordo", nome_imagem="imgs/short4fem.jpg")
produto48 = Produto(descricao = "Shorts Jeans", situacao = "Situação: Seminovo", cor ="Jeans", nome_imagem="imgs/short5fem.jpg")
produto49 = Produto(descricao = "Shorts Jeans", situacao = "Situação: Seminovo", cor ="Preto", nome_imagem="imgs/short6fem.jpg")
produto50 = Produto(descricao = "Shorts com blusa", situacao = "Situação: Seminovo", cor ="Florido", nome_imagem="imgs/short7fem.jpg")
produto51 = Produto(descricao = "Shorts Jeans", situacao = "Situação: Seminovo", cor ="Jeans", nome_imagem="imgs/short8fem.jpg")
produto52 = Produto(descricao = "Shorts Social", situacao = "Situação: Seminovo", cor ="Azul", nome_imagem="imgs/short9fem.jpg")

produto53 = Produto(descricao = "Saia", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/saia1.png")
produto54 = Produto(descricao = "Saia", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/saia2.png")
produto55 = Produto(descricao = "Saia", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/saia3.png")
produto56 = Produto(descricao = "Saia", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/saia4.png")
produto57 = Produto(descricao = "Saia", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/saia5.png")
produto58 = Produto(descricao = "Saia", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/saia6.png")

produto59 = Produto(descricao = "Camisa", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/camisa1.jpg")
produto60 = Produto(descricao = "Camisa", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/camisa2.jpg")
produto61 = Produto(descricao = "Camisa", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/camisa3.jpg")
produto62 = Produto(descricao = "Camisa", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/camisa4.jpg")
produto63 = Produto(descricao = "Camisa", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/camisa5.jpg")
produto64 = Produto(descricao = "Camisa", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/camisa6.jpg")
produto65 = Produto(descricao = "Camisa", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/camisa7.jpg")

produto66 = Produto(descricao = "Regata", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/regata.jpg")
produto67 = Produto(descricao = "Bermuda", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/bermuda.jpg")

produto68 = Produto(descricao = "Blusa", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/blusa33.jpeg")
produto69 = Produto(descricao = "Blusa", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/blusa34.jpeg")
produto70 = Produto(descricao = "Vestido", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/vestido2.jpeg")
produto71 = Produto(descricao = "Saia", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/saia7.jpeg")
produto72 = Produto(descricao = "Camisa", situacao = "Situação: Seminovo", cor ="", nome_imagem="imgs/camisa8.jpeg")





with app.app_context():
    db.create_all()
    db.session.add(produto1)
    db.session.add(produto2)
    db.session.add(produto3)
    db.session.add(produto4)
    db.session.add(produto5)
    db.session.add(produto6)
    db.session.add(produto7)
    db.session.add(produto8)
    db.session.add(produto9)
    db.session.add(produto10)
    db.session.add(produto11)
    db.session.add(produto12)
    db.session.add(produto13)
    db.session.add(produto14)
    db.session.add(produto15)
    db.session.add(produto16)
    db.session.add(produto17)
    db.session.add(produto18)
    db.session.add(produto19)
    db.session.add(produto20)
    db.session.add(produto21)
    db.session.add(produto22)
    db.session.add(produto23)
    db.session.add(produto24)
    db.session.add(produto25)
    db.session.add(produto26)
    db.session.add(produto27)
    db.session.add(produto28)
    db.session.add(produto29)
    db.session.add(produto30)
    db.session.add(produto31)
    db.session.add(produto32)
    db.session.add(produto33)
    db.session.add(produto34)
    db.session.add(produto35)
    db.session.add(produto36)
    db.session.add(produto37)
    db.session.add(produto38)
    db.session.add(produto39)
    db.session.add(produto40)
    db.session.add(produto41)
    db.session.add(produto42)
    db.session.add(produto43)
    db.session.add(produto44)
    db.session.add(produto45)
    db.session.add(produto46)
    db.session.add(produto47)
    db.session.add(produto48)
    db.session.add(produto49)
    db.session.add(produto50)
    db.session.add(produto51)
    db.session.add(produto52)
    db.session.add(produto53)
    db.session.add(produto54)
    db.session.add(produto55)
    db.session.add(produto56)
    db.session.add(produto57)
    db.session.add(produto58)
    db.session.add(produto59)
    db.session.add(produto60)
    db.session.add(produto61)
    db.session.add(produto62)
    db.session.add(produto63)
    db.session.add(produto64)
    db.session.add(produto65)
    db.session.add(produto66)
    db.session.add(produto67)
    db.session.add(produto68)
    db.session.add(produto69)
    db.session.add(produto70)
    db.session.add(produto71)
    db.session.add(produto72)



    db.session.commit()
    print("bd salvo")
    print(produto1.json())

